freebsd_instance:
  image_family: freebsd-14-2

task:
  install_script: pkg install -y gmake
  build_script:
    - gmake clean
    - gmake
  test_script:
    - ./sfetch --logo freebsd
    - ./sfetch --logo openbsd
    - ./sfetch --logo void
    - ./scat --help
    - ./sls --help
    - ./sfetch 2>&1 | grep -q "os"
    - ./sfetch 2>&1 | grep -q "kernel"
    - ./sfetch 2>&1 | grep -q "uptime"
